# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: world.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='world.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0bworld.proto\"2\n\x0fPBMapCoordinate\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\t\n\x01z\x18\x03 \x02(\x05\"T\n\x06PBRect\x12\"\n\x08top_left\x18\x01 \x02(\x0b\x32\x10.PBMapCoordinate\x12&\n\x0c\x62ottom_right\x18\x02 \x02(\x0b\x32\x10.PBMapCoordinate\"[\n\tPBTilemap\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x15\n\x04rect\x18\x02 \x02(\x0b\x32\x07.PBRect\x12\r\n\x05level\x18\x03 \x02(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x02(\x0c\x12\x0c\n\x04type\x18\x05 \x02(\x05\"L\n\x0cPBWorldChunk\x12\x1f\n\x05\x63oord\x18\x01 \x02(\x0b\x32\x10.PBMapCoordinate\x12\x1b\n\x07tilemap\x18\x02 \x03(\x0b\x32\n.PBTilemap\"(\n\x07PBWorld\x12\x1d\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\r.PBWorldChunk')
)




_PBMAPCOORDINATE = _descriptor.Descriptor(
  name='PBMapCoordinate',
  full_name='PBMapCoordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='PBMapCoordinate.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='PBMapCoordinate.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='PBMapCoordinate.z', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=65,
)


_PBRECT = _descriptor.Descriptor(
  name='PBRect',
  full_name='PBRect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='top_left', full_name='PBRect.top_left', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bottom_right', full_name='PBRect.bottom_right', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=151,
)


_PBTILEMAP = _descriptor.Descriptor(
  name='PBTilemap',
  full_name='PBTilemap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PBTilemap.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rect', full_name='PBTilemap.rect', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='PBTilemap.level', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='PBTilemap.data', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='PBTilemap.type', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=244,
)


_PBWORLDCHUNK = _descriptor.Descriptor(
  name='PBWorldChunk',
  full_name='PBWorldChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coord', full_name='PBWorldChunk.coord', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tilemap', full_name='PBWorldChunk.tilemap', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=322,
)


_PBWORLD = _descriptor.Descriptor(
  name='PBWorld',
  full_name='PBWorld',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunks', full_name='PBWorld.chunks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=364,
)

_PBRECT.fields_by_name['top_left'].message_type = _PBMAPCOORDINATE
_PBRECT.fields_by_name['bottom_right'].message_type = _PBMAPCOORDINATE
_PBTILEMAP.fields_by_name['rect'].message_type = _PBRECT
_PBWORLDCHUNK.fields_by_name['coord'].message_type = _PBMAPCOORDINATE
_PBWORLDCHUNK.fields_by_name['tilemap'].message_type = _PBTILEMAP
_PBWORLD.fields_by_name['chunks'].message_type = _PBWORLDCHUNK
DESCRIPTOR.message_types_by_name['PBMapCoordinate'] = _PBMAPCOORDINATE
DESCRIPTOR.message_types_by_name['PBRect'] = _PBRECT
DESCRIPTOR.message_types_by_name['PBTilemap'] = _PBTILEMAP
DESCRIPTOR.message_types_by_name['PBWorldChunk'] = _PBWORLDCHUNK
DESCRIPTOR.message_types_by_name['PBWorld'] = _PBWORLD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PBMapCoordinate = _reflection.GeneratedProtocolMessageType('PBMapCoordinate', (_message.Message,), dict(
  DESCRIPTOR = _PBMAPCOORDINATE,
  __module__ = 'world_pb2'
  # @@protoc_insertion_point(class_scope:PBMapCoordinate)
  ))
_sym_db.RegisterMessage(PBMapCoordinate)

PBRect = _reflection.GeneratedProtocolMessageType('PBRect', (_message.Message,), dict(
  DESCRIPTOR = _PBRECT,
  __module__ = 'world_pb2'
  # @@protoc_insertion_point(class_scope:PBRect)
  ))
_sym_db.RegisterMessage(PBRect)

PBTilemap = _reflection.GeneratedProtocolMessageType('PBTilemap', (_message.Message,), dict(
  DESCRIPTOR = _PBTILEMAP,
  __module__ = 'world_pb2'
  # @@protoc_insertion_point(class_scope:PBTilemap)
  ))
_sym_db.RegisterMessage(PBTilemap)

PBWorldChunk = _reflection.GeneratedProtocolMessageType('PBWorldChunk', (_message.Message,), dict(
  DESCRIPTOR = _PBWORLDCHUNK,
  __module__ = 'world_pb2'
  # @@protoc_insertion_point(class_scope:PBWorldChunk)
  ))
_sym_db.RegisterMessage(PBWorldChunk)

PBWorld = _reflection.GeneratedProtocolMessageType('PBWorld', (_message.Message,), dict(
  DESCRIPTOR = _PBWORLD,
  __module__ = 'world_pb2'
  # @@protoc_insertion_point(class_scope:PBWorld)
  ))
_sym_db.RegisterMessage(PBWorld)


# @@protoc_insertion_point(module_scope)
